
// Types should be imported directly from ./content-types to avoid server action transformation issues
import type { Subject, Topic, Lesson } from "./content-types";

// Subject metadata (non-structural info that doesn't affect routing)
const SUBJECT_META: Record<string, { description: string; icon: string; color: string; label: string }> = {
  "artificial-intelligence": {
    description: "Master Artificial Intelligence from foundations to advanced agentic systems",
    icon: "🧠",
    color: "from-indigo-500 to-purple-600",
    label: "Artificial Intelligence (AI)",
  },
  dsa: {
    description: "Master Data Structures & Algorithms from fundamentals to advanced techniques",
    icon: "⚡",
    color: "from-orange-500 to-red-600",
    label: "Data Structures & Algorithms",
  },
  cse: {
    description: "Core Computer Science fundamentals: OS, DBMS, and Computer Networks",
    icon: "💻",
    color: "from-emerald-500 to-teal-600",
    label: "Computer Science (CSE)",
  },
  ece: {
    description: "Electronics & Communication Engineering: Signals, Circuits, and Systems",
    icon: "📡",
    color: "from-rose-500 to-pink-600",
    label: "Electronics (ECE)",
  },
};

// Topic sort order for specific subjects
const TOPIC_ORDER: Record<string, string[]> = {
  dsa: [
    "cpp-fundamentals",
    "problem-solving-basics",
    "time-space-complexity",
    "arrays",
    "strings",
    "searching-sorting",
    "hashing",
    "recursion-backtracking",
    "linked-list",
    "stack-queue",
    "graphs",
    "dynamic-programming",
  ],
  "artificial-intelligence": [
    "ai-foundations",
    "machine-learning",
    "deep-learning",
    "transformers",
    "nlp",
    "computer-vision",
    "generative-ai",
    "agentic-ai",
    "reinforcement-learning",
    "deep-reinforcement-learning",
    "multimodal-ai",
    "mlops",
    "fine-tuning-adaptation",
    "rag-memory",
    "advanced-research",
  ],
  cse: [
    "roadmaps",
    "discrete-mathematics",
    "linear-algebra",
    "calculus",
    "probability-statistics",
    "numerical-methods",
    "digital-logic",
    "computer-organization-architecture",
    "c-programming",
    "data-structures",
    "algorithms",
    "theory-of-computation",
    "compiler-design",
    "operating-systems",
    "database-management-systems",
    "computer-networks",
    "general-aptitude",
    "practice",
    "interview-preparation",
    "resources",
    "projects-labs",
  ],
  ece: [
    "ece-roadmaps",
    "ece-linear-algebra",
    "ece-calculus",
    "differential-equations",
    "complex-analysis",
    "ece-probability-statistics",
    "ece-numerical-methods",
    "vector-calculus",
    "transforms",
    "network-theory",
    "signals-systems",
    "electronic-devices",
    "analog-circuits",
    "digital-circuits",
    "control-systems",
    "communications",
    "electromagnetics",
    "microprocessors-microcontrollers",
    "digital-signal-processing",
    "vlsi-design",
    "computer-organization",
    "ece-general-aptitude",
    "ece-practice",
    "ece-interview-preparation",
    "tools-software",
    "ece-projects-labs",
  ],
};

// Topic display name mapping
const TOPIC_LABELS: Record<string, string> = {
  "cpp-fundamentals": "C++ Fundamentals",
  "problem-solving-basics": "Problem Solving Basics",
  "time-space-complexity": "Time & Space Complexity",
  arrays: "Arrays",
  strings: "Strings",
  "recursion-backtracking": "Recursion & Backtracking",
  "linked-list": "Linked List",
  "stack-queue": "Stack & Queue",
  "searching-sorting": "Searching & Sorting",
  hashing: "Hashing",
  trees: "Trees",
  graphs: "Graphs",
  "dynamic-programming": "Dynamic Programming",
  "ai-foundations": "AI Foundations",
  "machine-learning": "Machine Learning",
  "deep-learning": "Deep Learning",
  "transformers": "Transformers",
  nlp: "Natural Language Processing (NLP)",
  "computer-vision": "Computer Vision (CV)",
  "generative-ai": "Generative AI",
  "agentic-ai": "Agentic AI",
  "reinforcement-learning": "Reinforcement Learning (RL)",
  "deep-reinforcement-learning": "Deep Reinforcement Learning (DRL)",
  "multimodal-ai": "Multimodal AI",
  mlops: "MLOps",
  "fine-tuning-adaptation": "Fine-Tuning & Adaptation",
  "rag-memory": "RAG & Memory",
  "advanced-research": "Advanced Research",
  "roadmaps": "Roadmaps",
  "discrete-mathematics": "Discrete Mathematics",
  "linear-algebra": "Linear Algebra",
  "calculus": "Calculus",
  "probability-statistics": "Probability & Statistics",
  "numerical-methods": "Numerical Methods",
  "digital-logic": "Digital Logic",
  "computer-organization-architecture": "Computer Organization & Architecture",
  "c-programming": "C Programming",
  "data-structures": "Data Structures",
  "algorithms": "Algorithms",
  "theory-of-computation": "Theory of Computation",
  "compiler-design": "Compiler Design",
  "operating-systems": "Operating Systems",
  "database-management-systems": "Database Management Systems",
  "computer-networks": "Computer Networks",
  "general-aptitude": "General Aptitude",
  "practice": "Practice",
  "interview-preparation": "Interview Preparation",
  "resources": "Resources",
  "projects-labs": "Projects & Labs",
  "ece-roadmaps": "Roadmaps",
  "ece-linear-algebra": "Linear Algebra",
  "ece-calculus": "Calculus",
  "ece-probability-statistics": "Probability & Statistics",
  "ece-numerical-methods": "Numerical Methods",
  "ece-general-aptitude": "General Aptitude",
  "ece-practice": "Practice",
  "ece-interview-preparation": "Interview Preparation",
  "ece-projects-labs": "Projects & Labs",
  "differential-equations": "Differential Equations",
  "complex-analysis": "Complex Analysis",
  "vector-calculus": "Vector Calculus",
  "transforms": "Transforms",
  "network-theory": "Network Theory",
  "signals-systems": "Signals & Systems",
  "electronic-devices": "Electronic Devices",
  "analog-circuits": "Analog Circuits",
  "digital-circuits": "Digital Circuits",
  "control-systems": "Control Systems",
  "communications": "Communications",
  "electromagnetics": "Electromagnetics",
  "microprocessors-microcontrollers": "Microprocessors & Microcontrollers",
  "digital-signal-processing": "Digital Signal Processing",
  "vlsi-design": "VLSI Design",
  "computer-organization": "Computer Organization",
  "tools-software": "Tools & Software",
};

// Manual sort order for lessons in specific topics
const LESSON_ORDER: Record<string, string[]> = {
  "cpp-fundamentals": [
    "introduction-to-cpp",
    "structure-of-cpp-program",
    "compilation-process",
    "input-output",
    "comments-in-cpp",
    "variables",
    "data-types",
    "type-modifiers",
    "constants-literals",
    "keywords-identifiers",
    "operators",
    "arithmetic-operators",
    "relational-operators",
    "logical-operators",
    "bitwise-operators",
    "assignment-operators",
    "increment-decrement-operators",
    "ternary-operator",
    "operator-precedence",
    "type-casting",
    "escape-sequences",
    "conditional-statements",
    "if-statement",
    "if-else-statement",
    "nested-if",
    "else-if-ladder",
    "switch-statement",
    "loops",
    "for-loop",
    "while-loop",
    "do-while-loop",
    "nested-loops",
    "loop-control",
    "functions",
    "function-declaration-definition",
    "function-calling",
    "parameters-arguments",
    "return-values",
    "default-arguments",
    "inline-functions",
    "function-overloading",
    "recursion",
    "variable-scope",
    "local-variables",
    "global-variables",
    "storage-classes",
    "arrays",
    "one-d-arrays",
    "two-d-arrays",
    "multidimensional-arrays",
    "character-arrays",
    "strings",
    "c-style-strings",
    "string-class",
    "string-functions",
    "pointers",
    "pointer-basics",
    "pointer-arithmetic",
    "pointers-and-arrays",
    "null-pointers",
    "dynamic-memory-allocation",
    "references",
    "reference-variables",
    "pass-by-reference",
    "structures",
    "unions",
    "enumerations",
    "typedef",
    "namespaces",
    "header-files",
    "preprocessor-directives",
    "macros",
    "file-handling",
    "reading-from-files",
    "writing-to-files",
    "oop-basics",
    "classes-objects",
    "access-specifiers",
    "constructors",
    "destructors",
    "copy-constructor",
    "this-pointer",
    "static-members",
    "friend-function",
    "inheritance",
    "types-of-inheritance",
    "polymorphism",
    "function-overriding",
    "virtual-functions",
    "abstraction",
    "encapsulation",
    "operator-overloading",
    "exception-handling",
    "templates",
    "function-templates",
    "class-templates",
    "stl-introduction",
    "vectors",
    "pairs",
    "iterators",
    "stl-algorithms",
    "stl-stack",
    "stl-queue",
    "stl-set",
    "stl-map",
    "stl-priority-queue",
    "stl-deque",
    "lambda-functions",
    "auto-keyword",
    "range-based-loops",
    "smart-pointers",
    "time-complexity-basics",
  ],
  "problem-solving-basics": [
    "introduction-to-problem-solving",
    "problem-understanding",
    "input-output-analysis",
    "constraints-analysis",
    "dry-run-technique",
    "brute-force-approach",
    "optimized-approach-thinking",
    "pattern-recognition",
    "breaking-problems-subproblems",
    "logical-thinking",
    "algorithmic-thinking",
    "pseudocode",
    "flowcharts",
    "basic-mathematics",
    "number-properties",
    "prime-numbers",
    "factors-and-multiples",
    "gcd-and-lcm",
    "modular-arithmetic-basics",
    "binary-number-basics",
    "bit-manipulation-basics",
    "time-complexity-basics",
    "space-complexity-basics",
    "best-average-worst-case",
    "iterative-thinking",
    "recursive-thinking",
    "simulation-problems",
    "greedy-basics",
    "two-pointer-basics",
    "sliding-window-basics",
    "prefix-sum-basics",
    "frequency-counting",
    "hashing-basics",
    "sorting-basics",
    "searching-basics",
    "binary-search-basics",
    "matrix-traversal-basics",
    "string-manipulation-basics",
    "array-manipulation-basics",
    "backtracking-basics",
    "divide-and-conquer-basics",
    "edge-case-handling",
    "overflow-handling",
    "debugging-techniques",
    "test-case-generation",
    "competitive-programming-basics",
    "stl-basics",
    "input-optimization",
    "code-readability",
    "problem-solving-patterns",
    "observation-building",
    "mathematical-observation",
    "constructive-thinking",
    "ad-hoc-problems",
    "implementation-problems",
    "optimization-techniques",
    "practice-strategy",
  ],
  "time-space-complexity": [
    "introduction-to-time-complexity",
    "introduction-to-space-complexity",
    "why-complexity-analysis",
    "input-size-growth-rate",
    "best-case-complexity",
    "average-case-complexity",
    "worst-case-complexity",
    "big-o-notation",
    "big-omega-notation",
    "big-theta-notation",
    "constant-time",
    "logarithmic-time",
    "linear-time",
    "linearithmic-time",
    "quadratic-time",
    "cubic-time",
    "exponential-time",
    "factorial-time",
    "complexity-comparison",
    "rules-for-calculating",
    "ignore-constants",
    "ignore-lower-order",
    "complexity-of-loops",
    "complexity-nested-loops",
    "complexity-sequential-loops",
    "complexity-recursion",
    "recurrence-relation-basics-complexity",
    "master-theorem-basics",
    "space-complexity-basics-tsc",
    "auxiliary-space",
    "input-space",
    "recursive-stack-space",
    "inplace-algorithms-complexity",
    "time-space-tradeoff",
    "complexity-arrays",
    "complexity-strings",
    "complexity-linked-lists",
    "complexity-stack",
    "complexity-queue",
    "complexity-hashing",
    "complexity-trees",
    "complexity-heap",
    "complexity-graph",
    "complexity-sorting",
    "complexity-searching",
    "amortized-complexity",
    "iterative-vs-recursive",
    "complexity-stl-containers",
    "complexity-stl-algorithms",
    "optimization-techniques-tsc",
    "brute-force-vs-optimized",
    "identifying-bottlenecks",
    "tle-basics",
    "mle-basics",
    "choosing-efficient-algorithms",
    "complexity-competitive-programming",
    "dry-run-complexity",
    "practice-complexity",
  ],
  "recursion-backtracking": [
    "introduction-to-recursion",
    "recursive-thinking",
    "base-case",
    "recursive-case",
    "recursive-function-calls",
    "call-stack",
    "stack-overflow",
    "dry-run-recursion",
    "tail-recursion",
    "head-recursion",
    "tree-recursion",
    "indirect-recursion",
    "nested-recursion",
    "parameterized-recursion",
    "functional-recursion",
    "recurrence-relation-basics",
    "time-complexity-recursion",
    "space-complexity-recursion",
    "recursive-pattern-problems",
    "print-numbers",
    "sum-of-n-numbers",
    "factorial",
    "fibonacci",
    "power-calculation",
    "reverse-array-recursion",
    "reverse-string-recursion",
    "palindrome-check-recursion",
    "binary-search-recursion",
    "recursion-on-arrays",
    "recursion-on-strings",
    "subsequence-problems",
    "generate-all-subsequences",
    "generate-all-subsets",
    "generate-power-set",
    "pick-not-pick",
    "multiple-recursion-calls",
    "backtracking-introduction",
    "recursion-vs-backtracking",
    "backtracking-template",
    "decision-tree-visualization",
    "state-space-tree",
    "undo-backtrack-step",
    "constraint-checking",
    "generate-all-permutations",
    "permutations-duplicates",
    "combination-sum",
    "combination-sum-ii",
    "subset-sum-recursion",
    "letter-combinations",
    "generate-parentheses",
    "n-queens",
    "rat-in-a-maze",
    "sudoku-solver",
    "word-search",
    "m-coloring",
    "knights-tour",
    "maze-solving",
    "partition-problems",
    "palindrome-partitioning-recursion",
    "restore-ip-addresses",
    "expression-add-operators",
    "backtracking-on-grids",
    "backtracking-on-strings",
    "backtracking-on-arrays",
    "branch-and-bound-basics",
    "recursion-tree-method",
    "memoization-basics",
    "recursive-dp-intro",
    "practice-patterns-recursion",
    "practice-patterns-backtracking",
  ],
  "arrays": [
    "array-introduction",
    "array-traversal",
    "array-input-output",
    "reverse-array",
    "linear-search",
    "binary-search",
    "find-min-max",
    "move-zeros",
    "remove-duplicates",
    "two-sum",
    "sort-colors",
    "kadane-algorithm",
    "maximum-subarray-sum",
    "prefix-sum-basics",
    "range-sum-query",
    "equilibrium-index",
    "bubble-sort",
    "majority-element",
    "product-of-array-except-self",
    "next-permutation",
    "merge-intervals",
    "trapping-rain-water",
    "container-with-most-water",
    "maximum-product-subarray",
    "longest-subarray-k",
    "subarray-sum-equals-k",
    "fixed-window-sum",
    "minimum-window-substring",
    "largest-number",
  ],
  "linked-list": [
    "introduction-to-linked-list",
    "advantages-disadvantages",
    "types-of-linked-list",
    "singly-linked-list",
    "doubly-linked-list",
    "circular-linked-list",
    "circular-doubly-linked-list",
    "node-structure",
    "memory-representation",
    "dynamic-memory-allocation",
    "traversal",
    "insertion-at-beginning",
    "insertion-at-end",
    "insertion-at-position",
    "deletion-from-beginning",
    "deletion-from-end",
    "deletion-by-value",
    "deletion-by-position",
    "searching",
    "updating-nodes",
    "length",
    "reverse-linked-list",
    "recursive-reversal",
    "middle-of-linked-list",
    "detect-loop",
    "floyd-cycle-detection",
    "loop-start-point",
    "remove-loop",
    "merge-sorted-lists",
    "sort-linked-list",
    "merge-sort-linked-list",
    "remove-duplicates-sorted",
    "remove-duplicates-unsorted",
    "nth-node-from-end",
    "delete-nth-node-from-end",
    "check-palindrome",
    "odd-even-linked-list",
    "segregate-even-odd",
    "intersection-of-lists",
    "intersection-point",
    "add-two-numbers",
    "multiply-linked-lists",
    "flatten-linked-list",
    "rotate-linked-list",
    "clone-with-random-pointer",
    "partition-linked-list",
    "swap-nodes-in-pairs",
    "reverse-in-k-groups",
    "circular-operations",
    "doubly-operations",
    "insertion-in-dll",
    "deletion-in-dll",
    "reverse-dll",
    "lru-using-dll",
    "stack-using-linked-list",
    "queue-using-linked-list",
    "header-linked-list",
    "sparse-matrix-linked-list",
    "polynomial-linked-list",
    "skip-list-basics",
    "xor-linked-list-basics",
    "stl-list",
    "iterator-linked-list",
    "practice-patterns",
  ],
  "searching-sorting": [
    "introduction-to-searching",
    "linear-search-searching",
    "binary-search-searching",
    "binary-search-descending",
    "order-agnostic-binary-search",
    "lower-bound",
    "upper-bound",
    "floor-and-ceil",
    "first-occurrence",
    "last-occurrence",
    "count-occurrences",
    "search-insert-position",
    "binary-search-on-answer",
    "peak-element",
    "search-in-rotated-array",
    "search-in-nearly-sorted",
    "min-in-rotated-array",
    "single-element-sorted",
    "sqrt-binary-search",
    "nth-root-binary-search",
    "allocate-minimum-pages",
    "aggressive-cows",
    "painters-partition",
    "koko-eating-bananas",
    "capacity-to-ship-packages",
    "median-two-sorted-arrays",
    "search-2d-matrix",
    "row-with-max-ones",
    "introduction-to-sorting",
    "stability-in-sorting",
    "inplace-vs-outplace-sorting",
    "adaptive-sorting",
    "internal-vs-external-sorting",
    "bubble-sort",
    "selection-sort",
    "insertion-sort",
    "merge-sort",
    "quick-sort",
    "heap-sort",
    "counting-sort",
    "radix-sort",
    "bucket-sort",
    "shell-sort",
    "recursive-sorting",
    "iterative-sorting",
    "partitioning-techniques",
    "lomuto-partition",
    "hoare-partition",
    "dutch-national-flag",
    "quick-select",
    "kth-smallest-element",
    "kth-largest-element",
    "sort-012",
    "merge-two-sorted-arrays",
    "inversion-count",
    "reverse-pairs",
    "external-sorting-basics",
    "stl-sort",
    "custom-comparator",
    "stable-sort",
    "partial-sort",
    "binary-search-stl",
    "lower-upper-bound-stl",
    "two-pointer-sorting",
    "greedy-sorting",
    "practice-patterns-searching",
    "practice-patterns-sorting",
  ],
  "stack-queue": [
    "introduction-to-stack",
    "stack-data-structure",
    "lifo-principle",
    "stack-operations",
    "push-operation",
    "pop-operation",
    "peek-top-operation",
    "isempty-isfull",
    "stack-arrays",
    "stack-linked-list",
    "dynamic-stack",
    "complexity-stack",
    "applications-stack",
    "balanced-parentheses",
    "valid-parentheses",
    "infix-expression",
    "prefix-expression",
    "postfix-expression",
    "infix-to-postfix",
    "infix-to-prefix",
    "postfix-to-infix",
    "prefix-to-infix",
    "evaluate-postfix",
    "evaluate-prefix",
    "recursion-call-stack",
    "backtracking-stack",
    "monotonic-stack",
    "next-greater-element",
    "next-smaller-element",
    "previous-greater-element",
    "previous-smaller-element",
    "stock-span",
    "largest-rectangle-histogram",
    "maximal-rectangle",
    "trapping-rain-water",
    "min-stack",
    "special-stack",
    "stack-using-queue",
    "two-stack-one-array",
    "multiple-stack-problems",
    "introduction-to-queue",
    "queue-data-structure",
    "fifo-principle",
    "queue-operations",
    "enqueue-operation",
    "dequeue-operation",
    "front-and-rear",
    "queue-arrays",
    "queue-linked-list",
    "circular-queue",
    "dynamic-queue",
    "deque-basics",
    "priority-queue-intro",
    "queue-using-stack",
    "stack-using-queue-queue",
    "applications-queue",
    "cpu-scheduling",
    "printer-queue",
    "bfs-using-queue",
    "sliding-window-max",
    "first-negative-window",
    "circular-tour",
    "lru-cache-queue",
    "k-queue-one-array",
    "priority-queue-heap",
    "stl-stack",
    "stl-queue",
    "stl-deque",
    "stl-priority-queue-stl",
    "monotonic-queue",
    "practice-patterns-stack",
    "practice-patterns-queue",
  ],
  strings: [
    "introduction-to-strings",
    "character-arrays-strings",
    "string-input-output",
    "string-traversal",
    "string-length",
    "string-concatenation",
    "string-comparison",
    "string-copy",
    "reverse-string",
    "palindrome-string",
    "toggle-case",
    "case-conversion",
    "remove-spaces",
    "count-vowels-consonants",
    "frequency-of-characters",
    "ascii-values",
    "character-hashing-strings",
    "string-searching",
    "substrings",
    "subsequence-vs-substring",
    "string-sorting",
    "lexicographical-order",
    "anagram-check",
    "rotate-string",
    "string-compression",
    "run-length-encoding",
    "remove-duplicates-string",
    "longest-common-prefix",
    "longest-palindromic-substring",
    "longest-palindromic-subsequence",
    "count-palindromic-substrings",
    "string-matching-basics",
    "naive-pattern-matching",
    "rabin-karp-algorithm-strings",
    "kmp-algorithm",
    "z-algorithm",
    "prefix-function-lps",
    "string-hashing-strings",
    "polynomial-rolling-hash-strings",
    "double-hashing-strings",
    "pattern-searching-problems",
    "wildcard-matching-strings",
    "regular-expression-basics",
    "sliding-window-strings",
    "longest-substring-no-repeat",
    "minimum-window-substring",
    "permutation-in-string",
    "group-anagrams-strings",
    "count-and-say",
    "string-to-integer",
    "integer-to-string",
    "string-streams",
    "tokenization",
    "split-string",
    "parsing-strings",
    "compare-version-numbers",
    "roman-to-integer",
    "integer-to-roman",
    "multiply-large-numbers",
    "binary-string-problems",
    "parentheses-string-problems",
    "balanced-string-problems",
    "edit-distance-strings",
    "distinct-subsequences-strings",
    "string-dp-basics",
    "trie-basics-strings",
    "suffix-array-basics",
    "suffix-trie-basics",
    "stl-string-functions",
    "practice-patterns-strings",
  ],
  trees: [
    "introduction-to-trees",
    "tree-terminology",
    "root-node",
    "parent-node",
    "child-node",
    "sibling-node",
    "leaf-node",
    "internal-node",
    "ancestor-descendant",
    "degree-of-node",
    "height-of-tree",
    "depth-of-node",
    "level-of-node",
    "subtree",
    "types-of-trees",
    "binary-tree",
    "full-binary-tree",
    "complete-binary-tree",
    "perfect-binary-tree",
    "balanced-binary-tree",
    "degenerate-binary-tree",
    "skewed-binary-tree",
    "bst-basics",
    "avl-tree",
    "red-black-tree",
    "heap-basics",
    "trie-basics",
    "segment-tree-basics",
    "fenwick-tree-basics",
    "n-ary-tree",
    "tree-representation",
    "array-representation",
    "linked-representation",
    "tree-traversal-basics",
    "dfs-traversal",
    "bfs-traversal",
    "preorder-traversal",
    "inorder-traversal",
    "postorder-traversal",
    "level-order-traversal",
    "recursive-traversals",
    "iterative-traversals",
    "morris-traversal",
    "binary-tree-construction",
    "construct-from-traversals",
    "serialize-deserialize",
    "count-nodes",
    "sum-of-nodes",
    "height-binary-tree",
    "diameter-binary-tree",
    "max-depth",
    "min-depth",
    "balanced-binary-tree-check",
    "identical-trees",
    "symmetric-tree",
    "mirror-tree",
    "invert-binary-tree",
    "lca-binary-tree",
    "path-in-trees",
    "root-to-node-path",
    "root-to-leaf-paths",
    "max-path-sum",
    "children-sum-property",
    "boundary-traversal",
    "vertical-order-traversal",
    "top-view",
    "bottom-view",
    "left-view",
    "right-view",
    "zigzag-traversal",
    "diagonal-traversal",
    "search-in-bst",
    "insert-in-bst",
    "delete-in-bst",
    "floor-in-bst",
    "ceil-in-bst",
    "kth-smallest-bst",
    "kth-largest-bst",
    "validate-bst",
    "lca-bst",
    "inorder-successor-predecessor",
    "bst-iterator",
    "recover-bst",
    "merge-two-bsts",
    "min-heap",
    "max-heap",
    "heap-operations",
    "heapify",
    "build-heap",
    "heap-sort",
    "priority-queue",
    "kth-largest-smallest-heap",
    "merge-k-sorted-arrays",
    "merge-k-sorted-lists",
    "insert-in-trie",
    "search-in-trie",
    "prefix-search",
    "word-dictionary",
    "lcp-using-trie",
    "range-sum-query",
    "range-min-query",
    "lazy-propagation",
    "prefix-sum-queries",
    "update-queries",
    "tree-dp-basics-tree",
    "dp-on-trees",
    "binary-lifting",
    "euler-tour",
    "heavy-light-decomposition",
    "dsu-tree",
    "practice-patterns-trees",
  ],
  hashing: [
    "introduction-to-hashing",
    "need-for-hashing",
    "hash-function",
    "good-hash-function",
    "hash-table",
    "direct-addressing",
    "collision-in-hashing",
    "collision-resolution",
    "separate-chaining",
    "open-addressing",
    "linear-probing",
    "quadratic-probing",
    "double-hashing",
    "rehashing",
    "load-factor",
    "time-complexity-hashing",
    "hashmap-unordered-map",
    "hashset-unordered-set",
    "frequency-array",
    "frequency-map",
    "counting-frequencies",
    "prefix-sum-hashing",
    "hashing-pair-problems",
    "duplicate-detection",
    "subarray-problems-hashing",
    "longest-subarray-sum-k",
    "count-subarrays-sum-k",
    "longest-consecutive-sequence",
    "two-sum-hashing",
    "three-sum-basics",
    "group-anagrams",
    "first-non-repeating-char",
    "sliding-window-hashing",
    "string-hashing-intro",
    "character-hashing",
    "integer-hashing",
    "custom-hash-functions",
    "ordered-vs-unordered-map",
    "set-vs-unordered-set",
    "multiset-unordered-multiset",
    "hashing-in-stl",
    "bucket-concept",
    "iterating-hashmaps",
    "hashing-for-caching",
    "lru-cache-basics",
    "polynomial-rolling-hash",
    "string-hashing",
    "rabin-karp-algorithm",
    "double-hashing-strings",
    "hash-collision-strings",
    "prefix-hashing",
    "pattern-matching-hashing",
    "bitmask-hashing",
    "coordinate-compression-hashing",
    "hashing-greedy-problems",
    "hashing-binary-search-problems",
    "hashing-practice-patterns",
  ],
  graphs: [
    "graph-definition",
    "vertices-and-edges",
    "graph-degrees",
    "types-of-graphs",
    "adjacency-list",
    "adjacency-matrix",
    "bfs",
    "dfs",
    "connected-components",
    "flood-fill",
    "number-of-islands",
    "cycle-detection-undirected",
    "cycle-detection-directed",
    "bipartite-graph",
    "topological-sort-dfs",
    "topological-sort-kahns",
    "shortest-path-unweighted",
    "dijkstra-algorithm",
    "shortest-path-dag",
    "bellman-ford-algorithm",
    "floyd-warshall-algorithm",
    "mst-kruskal",
    "mst-prim",
    "disjoint-set-union",
    "scc-kosaraju",
    "scc-tarjan",
    "bridges",
    "articulation-points",
    "zero-one-bfs",
    "multi-source-bfs",
    "grid-based-graphs",
    "shortest-path-matrix",
    "rotten-oranges",
    "word-ladder",
    "course-schedule",
    "alien-dictionary",
    "clone-graph",
    "detect-cycle-grid",
    "euler-path-circuit",
    "hamiltonian-path-cycle",
    "graph-coloring",
    "network-flow",
    "transitive-closure",
    "graph-condensation",
    "complexity-graph-algorithms",
  ],
  "dynamic-programming": [
    "introduction-to-dp",
    "recursion-vs-dp",
    "overlapping-subproblems",
    "optimal-substructure",
    "memoization",
    "tabulation",
    "space-optimization",
    "state-definition",
    "transition-relation",
    "base-cases",
    "dp-on-1d-arrays",
    "fibonacci-dp",
    "climbing-stairs",
    "frog-jump",
    "house-robber",
    "min-cost-climbing-stairs",
    "coin-change",
    "perfect-squares",
    "decode-ways",
    "integer-break",
    "dp-on-2d-grids",
    "grid-unique-paths",
    "unique-paths-obstacles",
    "minimum-path-sum",
    "triangle-minimum-path-sum",
    "maximum-path-sum-matrix",
    "cherry-pickup",
    "dp-on-subsequences",
    "subset-sum",
    "partition-equal-subset-sum",
    "count-subsets-sum-k",
    "zero-one-knapsack",
    "unbounded-knapsack",
    "rod-cutting",
    "coin-change-i",
    "coin-change-ii",
    "target-sum",
    "dp-on-strings",
    "longest-common-subsequence",
    "print-lcs",
    "longest-common-substring",
    "shortest-common-supersequence",
    "edit-distance",
    "wildcard-matching",
    "distinct-subsequences",
    "palindrome-partitioning",
    "longest-palidromic-subsequence",
    "dp-on-lis-pattern",
    "longest-increasing-subsequence",
    "print-lis",
    "largest-divisible-subset",
    "longest-string-chain",
    "bitonic-subsequence",
    "number-of-lis",
    "dp-on-stocks",
    "best-time-to-buy-sell-stock-i",
    "best-time-to-buy-sell-stock-ii",
    "stock-with-cooldown",
    "stock-with-transaction-fee",
    "best-time-to-buy-sell-stock-iii",
    "best-time-to-buy-sell-stock-iv",
    "dp-on-partition",
    "matrix-chain-multiplication",
    "burst-balloons",
    "min-cost-cut-stick",
    "boolean-parenthesization",
    "partition-array-max-sum",
    "dp-on-trees",
    "tree-dp-basics",
    "diameter-based-dp",
    "max-path-sum-tree",
    "house-robber-tree",
    "dp-on-graphs",
    "dag-dp",
    "bitmask-dp",
    "tsp",
    "digit-dp",
    "probability-dp",
    "game-theory-dp",
    "interval-dp",
    "state-compression-dp",
    "rerooting-dp",
    "dp-with-binary-search",
    "dp-optimization-techniques",
    "kadanes-algorithm-dp",
    "divide-and-conquer-optimization",
    "knuth-optimization",
    "convex-hull-trick",
    "sos-dp",
    "bitmasking-plus-dp",
    "problem-recognition",
  ],
  roadmaps: [
    "gate-cse-roadmap",
    "subject-wise-roadmap",
    "revision-roadmap",
    "placement-vs-gate",
    "interview-roadmap",
  ],
  "discrete-mathematics": [
    "propositional-logic",
    "predicate-logic",
    "set-theory",
    "relations-functions",
    "combinatorics",
    "graph-theory",
    "recurrence-relations",
    "algebraic-structures",
  ],
  "linear-algebra": [
    "matrices",
    "determinants",
    "rank-of-matrix",
    "eigenvalues-eigenvectors",
    "linear-equations",
  ],
  calculus: [
    "limits-continuity",
    "differentiation",
    "integration",
    "maxima-minima",
    "partial-derivatives",
  ],
  "probability-statistics": [
    "probability",
    "conditional-probability",
    "bayes-theorem",
    "random-variables",
    "distributions",
    "mean-variance",
    "correlation-regression",
  ],
  "numerical-methods": [
    "root-finding",
    "interpolation",
    "numerical-integration",
    "approximation-methods",
  ],
  "digital-logic": [
    "boolean-algebra",
    "logic-gates",
    "k-maps",
    "combinational-circuits",
    "sequential-circuits",
    "flip-flops",
    "counters-registers",
    "number-system",
    "memory-elements",
  ],
  "computer-organization-architecture": [
    "machine-instructions",
    "cpu-architecture",
    "pipelining",
    "addressing-modes",
    "memory-organization",
    "cache-memory",
    "io-organization",
    "risc-vs-cisc",
    "parallel-processing",
  ],
  "c-programming": [
    "pointers",
    "recursion",
    "dynamic-memory",
    "file-handling",
  ],
  "data-structures": [
    "arrays",
    "linked-lists",
    "stacks-queues",
    "hashing",
    "trees",
    "heaps",
    "graphs",
    "tries",
    "disjoint-set-union",
  ],
  algorithms: [
    "asymptotic-analysis",
    "divide-conquer",
    "greedy-algorithms",
    "dynamic-programming",
    "backtracking",
    "branch-bound",
    "graph-algorithms",
    "string-algorithms",
    "complexity-theory",
  ],
  "theory-of-computation": [
    "regular-languages",
    "finite-automata",
    "regular-expressions",
    "context-free-grammar",
    "pushdown-automata",
    "turing-machines",
    "decidability",
    "computability",
    "pumping-lemma",
  ],
  "compiler-design": [
    "lexical-analysis",
    "parsing",
    "syntax-directed-translation",
    "intermediate-code-generation",
    "runtime-environment",
    "code-optimization",
    "code-generation",
  ],
  "operating-systems": [
    "process-management",
    "threads",
    "cpu-scheduling",
    "synchronization",
    "deadlocks",
    "memory-management",
    "virtual-memory",
    "paging-segmentation",
    "file-systems",
    "disk-scheduling",
  ],
  "database-management-systems": [
    "er-model",
    "relational-model",
    "sql",
    "relational-algebra",
    "normalization",
    "transactions",
    "concurrency-control",
    "indexing",
    "query-processing",
  ],
  "computer-networks": [
    "osi-model",
    "tcp-ip",
    "physical-layer",
    "data-link-layer",
    "network-layer",
    "transport-layer",
    "application-layer",
    "routing-algorithms",
    "congestion-control",
    "network-security-basics",
  ],
  "general-aptitude": [
    "verbal-ability",
    "reading-comprehension",
    "grammar",
    "numerical-ability",
    "percentages",
    "ratios",
    "time-work",
    "probability",
    "logical-reasoning",
  ],
  practice: [
    "topic-wise-questions",
    "pyqs",
    "subject-tests",
    "mixed-tests",
    "mock-tests",
    "revision-sheets",
    "formula-notes",
    "short-notes",
  ],
  "interview-preparation": [
    "cs-core-interviews",
    "system-design-basics",
    "hr-interview",
    "resume-projects",
    "gate-to-placement",
  ],
  resources: [
    "standard-books",
    "lecture-notes",
    "cheatsheets",
    "youtube-playlists",
    "research-links",
  ],
  "projects-labs": [
    "os-lab",
    "dbms-lab",
    "cn-lab",
    "compiler-lab",
    "mini-projects",
  ],
  "differential-equations": [
    "first-order-odes",
    "separable-equations",
    "exact-equations-and-integrating-factors",
    "bernoulli-equations",
    "higher-order-linear-odes",
    "homogeneous-equations-with-constant-coefficients",
    "method-of-undetermined-coefficients",
    "variation-of-parameters",
    "cauchy-euler-equations",
    "systems-of-odes",
    "applications-in-circuits",
  ],
  "complex-analysis": [
    "complex-numbers-and-argand-plane",
    "analytic-functions",
    "cauchy-riemann-equations",
    "harmonic-functions",
    "complex-integration",
    "cauchys-integral-theorem",
    "cauchys-integral-formula",
    "taylors-and-laurents-series",
    "singularities-and-poles",
    "residue-theorem",
    "conformal-mapping",
  ],
  "vector-calculus": [
    "scalar-and-vector-fields",
    "gradient-divergence-curl",
    "line-integrals",
    "surface-integrals",
    "volume-integrals",
    "greens-theorem",
    "stokes-theorem",
    "divergence-theorem-gauss",
    "conservative-fields-and-potentials",
  ],
  "transforms": [
    "fourier-series-continuous",
    "dirichlet-conditions",
    "fourier-series-complex-form",
    "continuous-fourier-transform",
    "fourier-transform-properties",
    "inverse-fourier-transform",
    "convolution-theorem",
    "parsevals-theorem",
    "fourier-transform-pairs",
    "applications-in-signals",
    "definition-and-region-of-convergence",
    "laplace-transform-pairs",
    "laplace-transform-properties",
    "inverse-laplace-transform",
    "partial-fraction-expansion",
    "solving-odes-using-laplace",
    "initial-and-final-value-theorems",
    "applications-in-circuit-analysis",
    "definition-and-roc",
    "z-transform-pairs",
    "z-transform-properties",
    "inverse-z-transform",
    "partial-fractions-for-z-transform",
    "solving-difference-equations",
    "initial-and-final-value-theorems-z",
    "relationship-with-dtft",
  ],
  "network-theory": [
    "kvl-and-kcl-basics",
    "sign-conventions",
    "applications-in-dc-circuits",
    "applications-in-ac-circuits",
    "node-voltage-method",
    "supernodes",
    "nodal-analysis-with-dependent-sources",
    "nodal-analysis-ac-circuits",
    "mesh-current-method",
    "supermeshes",
    "mesh-analysis-with-dependent-sources",
    "comparison-nodal-vs-mesh",
    "thevenins-theorem",
    "nortons-theorem",
    "source-transformation",
    "maximum-power-transfer",
    "millmans-theorem",
    "rc-circuit-transients",
    "rl-circuit-transients",
    "rlc-circuit-transients",
    "initial-and-final-conditions",
    "step-and-impulse-response",
    "phasors-and-impedance",
    "resonance-series-parallel",
    "power-in-ac-circuits",
    "power-factor-correction",
    "three-phase-circuits",
    "z-parameters",
    "y-parameters",
    "h-parameters",
    "abcd-transmission-parameters",
    "inter-conversion-of-parameters",
    "interconnection-of-two-ports",
    "driving-point-functions",
    "transfer-functions",
    "poles-and-zeros",
    "graph-theory-for-networks",
    "network-topology",
  ],
  "signals-systems": [
    "signal-classification",
    "unit-step-ramp-impulse",
    "sinusoidal-and-exponential-signals",
    "signal-operations",
    "even-odd-decomposition",
    "discrete-time-signals",
    "unit-sample-unit-step-ramp",
    "discrete-signal-operations",
    "periodic-discrete-signals",
    "energy-and-power-signals",
    "continuous-time-convolution",
    "discrete-time-convolution",
    "convolution-properties",
    "graphical-convolution",
    "deconvolution",
    "nyquist-shannon-theorem",
    "aliasing",
    "reconstruction-of-signals",
    "anti-aliasing-filters",
    "practical-sampling",
    "linearity-and-time-invariance",
    "causality-and-stability",
    "impulse-response",
    "step-response",
    "bibo-stability",
    "frequency-response-of-lti-systems",
    "bode-plots-for-systems",
    "phase-and-group-delay",
    "ideal-filters",
    "distortion-in-systems",
  ],
  "electronic-devices": [
    "energy-band-theory",
    "intrinsic-semiconductors",
    "extrinsic-semiconductors",
    "carrier-concentration",
    "fermi-level",
    "drift-and-diffusion",
    "continuity-equation",
    "hall-effect",
    "recombination-generation",
    "pn-junction-formation",
    "depletion-region",
    "contact-potential",
    "forward-and-reverse-bias",
    "diode-equation",
    "junction-capacitance",
    "breakdown-mechanisms",
    "pn-junction-as-switch",
    "half-wave-rectifier",
    "full-wave-rectifier",
    "bridge-rectifier",
    "clippers-and-clampers",
    "zener-diode-regulator",
    "schottky-diode",
    "varactor-diode",
    "tunnel-diode",
    "led-and-photodiode",
    "bjt-structure-and-operation",
    "npn-and-pnp-transistors",
    "bjt-characteristics-curves",
    "current-gain-alpha-beta",
    "operating-regions",
    "ebers-moll-model",
    "bjt-as-switch",
    "mosfet-structure",
    "nmos-and-pmos",
    "threshold-voltage",
    "mosfet-iv-characteristics",
    "body-effect",
    "channel-length-modulation",
    "short-channel-effects",
    "mosfet-as-switch",
    "cmos-inverter",
    "cmos-logic-gates",
    "cmos-characteristics",
    "noise-margins",
    "power-dissipation",
    "cmos-scaling",
    "bjt-fixed-bias",
    "bjt-voltage-divider-bias",
    "bjt-self-bias",
    "dc-load-line",
    "q-point-stabilization",
    "mosfet-biasing",
    "thermal-stability",
    "bjt-small-signal-model",
    "hybrid-pi-model",
    "h-parameter-model",
    "mosfet-small-signal-model",
    "high-frequency-models",
    "gain-bandwidth-product",
  ],
  "analog-circuits": [
    "common-emitter-amplifier",
    "common-base-amplifier",
    "common-collector-emitter-follower",
    "common-source-amplifier",
    "common-gate-amplifier",
    "common-drain-source-follower",
    "multistage-amplifiers",
    "cascade-and-cascode",
    "gain-input-output-impedance",
    "frequency-response-of-amplifiers",
    "differential-pair-bjt",
    "differential-pair-mosfet",
    "differential-mode-gain",
    "common-mode-gain",
    "cmrr",
    "current-mirror",
    "active-load",
    "ideal-op-amp-characteristics",
    "inverting-amplifier",
    "non-inverting-amplifier",
    "summing-amplifier",
    "difference-amplifier",
    "integrator-and-differentiator",
    "instrumentation-amplifier",
    "voltage-follower",
    "comparator",
    "practical-op-amp-parameters",
    "slew-rate",
    "gain-bandwidth-product-op-amp",
    "feedback-concepts",
    "negative-feedback-advantages",
    "series-shunt-feedback",
    "shunt-series-feedback",
    "series-series-feedback",
    "shunt-shunt-feedback",
    "effect-on-gain-bandwidth",
    "effect-on-input-output-impedance",
    "oscillation-conditions-barkhausen",
    "rc-phase-shift-oscillator",
    "wien-bridge-oscillator",
    "colpitts-oscillator",
    "hartley-oscillator",
    "crystal-oscillator",
    "frequency-stability",
    "first-order-low-pass-filter",
    "first-order-high-pass-filter",
    "second-order-butterworth-filter",
    "chebyshev-filter",
    "band-pass-filter",
    "band-reject-notch-filter",
    "sallen-key-topology",
    "filter-order-and-response",
    "schmitt-trigger",
    "astable-multivibrator",
    "monostable-multivibrator",
    "bistable-multivibrator",
    "triangular-wave-generator",
    "sawtooth-wave-generator",
    "voltage-controlled-oscillator",
    "class-a-amplifier",
    "class-b-amplifier",
    "class-ab-amplifier",
    "class-c-amplifier",
    "class-d-amplifier",
    "push-pull-amplifier",
    "efficiency-calculations",
    "heat-dissipation",
  ],
  "digital-circuits": [
    "boolean-laws-and-theorems",
    "demorgans-theorem",
    "duality-principle",
    "sum-of-products-sop",
    "product-of-sums-pos",
    "canonical-forms",
    "boolean-function-minimization",
    "basic-gates-and-not-or-nand-nor",
    "universal-gates-nand-nor",
    "xor-and-xnor-gates",
    "gate-level-realization",
    "ttl-logic-family",
    "cmos-logic-family",
    "fan-in-fan-out",
    "propagation-delay-and-noise-margin",
    "2-variable-k-map",
    "3-variable-k-map",
    "4-variable-k-map",
    "grouping-rules",
    "dont-care-conditions",
    "sop-pos-minimization",
    "half-and-full-adder",
    "ripple-carry-adder",
    "carry-lookahead-adder",
    "subtractors",
    "multiplexers",
    "demultiplexers",
    "encoders-and-decoders",
    "priority-encoder",
    "binary-to-gray-code",
    "parity-generators-and-checkers",
    "magnitude-comparator",
    "multiplier-circuits",
    "latches-sr-d",
    "mealy-and-moore-machines",
    "state-table-and-diagram",
    "state-minimization",
    "state-assignment",
    "synchronous-vs-asynchronous",
    "sr-flip-flop",
    "d-flip-flop",
    "jk-flip-flop",
    "t-flip-flop",
    "master-slave-flip-flop",
    "flip-flop-conversions",
    "setup-and-hold-time",
    "clock-skew-and-metastability",
    "asynchronous-ripple-counter",
    "synchronous-counter",
    "up-down-counter",
    "mod-n-counter",
    "ring-counter",
    "johnson-counter",
    "shift-registers",
    "siso-sipo-piso-pipo",
    "universal-shift-register",
    "rom-types",
    "prom-eprom-eeprom",
    "flash-memory",
    "sram",
    "dram",
    "memory-organization",
    "memory-expansion",
    "dac-weighted-resistor",
    "dac-r2r-ladder",
    "adc-flash",
    "adc-successive-approximation",
    "adc-dual-slope",
    "adc-sigma-delta",
    "resolution-and-accuracy",
    "nyquist-criteria-for-adc",
    "pla",
    "pal",
    "cpld",
    "fpga-overview",
    "look-up-tables",
    "programmable-interconnects",
  ],
  "control-systems": [
    "laplace-representation",
    "poles-zeros-and-gain",
    "characteristic-equation",
    "transfer-function-of-physical-systems",
    "block-diagram-components",
    "block-diagram-reduction",
    "feedback-and-forward-paths",
    "closed-loop-transfer-function",
    "nodes-and-branches",
    "masons-gain-formula",
    "sfg-vs-block-diagram",
    "first-order-system-response",
    "second-order-system-response",
    "underdamped-overdamped-critically",
    "transient-response-specifications",
    "steady-state-error",
    "error-constants-kp-kv-ka",
    "type-of-system",
    "sinusoidal-transfer-function",
    "magnitude-and-phase-plots",
    "resonant-frequency-and-peak",
    "bandwidth",
    "correlation-time-frequency-response",
    "routh-hurwitz-criterion",
    "relative-stability",
    "gain-margin-and-phase-margin",
    "effects-of-adding-poles-zeros",
    "root-locus-rules",
    "construction-of-root-locus",
    "root-locus-for-design",
    "root-contours",
    "asymptotic-approximations",
    "factors-in-bode-plot",
    "gain-phase-margin-from-bode",
    "minimum-non-minimum-phase",
    "nyquist-plot",
    "nyquist-stability-criterion",
    "encirclement-and-poles",
    "gain-phase-margin-from-nyquist",
    "proportional-control",
    "integral-control",
    "derivative-control",
    "pid-tuning-methods",
    "ziegler-nichols-method",
    "lead-lag-compensators",
    "digital-pid-implementation",
  ],
  "communications": [
    "amplitude-modulation-basics",
    "am-waveform-and-spectrum",
    "modulation-index",
    "power-in-am",
    "dsb-sc",
    "ssb-modulation",
    "vsb-modulation",
    "am-demodulation-envelope-detector",
    "coherent-detection",
    "snr-analysis-am",
    "frequency-modulation-basics",
    "fm-waveform-and-spectrum",
    "modulation-index-fm",
    "bessel-functions-in-fm",
    "narrowband-wideband-fm",
    "fm-demodulation",
    "pre-emphasis-de-emphasis",
    "snr-advantage-of-fm",
    "phase-modulation-basics",
    "pm-vs-fm-comparison",
    "pm-spectrum",
    "pm-demodulation",
    "receiver-architecture",
    "intermediate-frequency",
    "image-frequency",
    "selectivity-and-sensitivity",
    "automatic-gain-control",
    "sampling-quantization-encoding",
    "uniform-and-nonuniform-quantization",
    "companding-mu-law-a-law",
    "pcm-bandwidth",
    "differential-pcm-dpcm",
    "nrz-rz-formats",
    "ami-coding",
    "manchester-coding",
    "hdb3-b8zs",
    "power-spectral-density-of-line-codes",
    "ask",
    "fsk",
    "psk-bpsk-qpsk",
    "qam",
    "dpsk",
    "ofdm",
    "bit-error-rate-analysis",
    "constellation-diagrams",
    "types-of-errors",
    "parity-check-codes",
    "hamming-codes",
    "cyclic-codes-crc",
    "bch-codes",
    "reed-solomon-codes",
    "convolutional-codes",
    "viterbi-algorithm",
    "turbo-codes-ldpc-overview",
    "entropy",
    "mutual-information",
    "channel-capacity-shannons-theorem",
    "source-coding-theorem",
    "huffman-coding",
    "lempel-ziv-coding",
    "rate-distortion-theory",
    "radio-wave-propagation",
    "path-loss-models",
    "fading-channels",
    "multipath-and-doppler",
    "diversity-techniques",
    "spread-spectrum-cdma",
    "cellular-systems-concepts",
    "mimo-overview",
    "satellite-orbits-geo-leo-meo",
    "link-budget",
    "transponders",
    "earth-station",
    "satellite-access-methods",
    "optical-fiber-structure",
    "types-of-optical-fiber",
    "attenuation-and-dispersion",
    "optical-sources-led-laser",
    "optical-detectors-pin-apd",
    "wdm-and-dwdm",
  ],
  "electromagnetics": [
    "coulombs-law",
    "electric-field-intensity",
    "gauss-law",
    "electric-potential",
    "poissons-and-laplaces-equation",
    "dielectrics-and-polarization",
    "boundary-conditions",
    "capacitance-calculations",
    "biot-savart-law",
    "amperes-circuital-law",
    "magnetic-flux-density",
    "magnetic-potential",
    "magnetic-materials",
    "boundary-conditions-magnetic",
    "inductance-calculations",
    "faradays-law",
    "displacement-current",
    "maxwells-equations-differential-form",
    "maxwells-equations-integral-form",
    "continuity-equation",
    "time-harmonic-fields",
    "wave-equation",
    "plane-waves-in-free-space",
    "plane-waves-in-lossy-medium",
    "polarization-of-waves",
    "poynting-theorem",
    "reflection-and-refraction",
    "snells-law-brewsters-angle",
    "telegrapher-equations",
    "characteristic-impedance",
    "voltage-current-waves",
    "reflection-coefficient",
    "vswr",
    "input-impedance",
    "smith-chart",
    "impedance-matching",
    "quarter-wave-transformer",
    "rectangular-waveguide",
    "circular-waveguide",
    "te-tm-tem-modes",
    "cutoff-frequency",
    "phase-and-group-velocity",
    "cavity-resonators",
    "antenna-parameters",
    "hertzian-dipole",
    "half-wave-dipole",
    "monopole-antenna",
    "antenna-arrays",
    "aperture-antennas",
    "horn-antenna",
    "parabolic-reflector",
    "friis-transmission-equation",
    "radar-range-equation",
    "microwave-frequencies-and-bands",
    "s-parameters",
    "microwave-network-analysis",
    "power-dividers-and-couplers",
    "microwave-filters",
    "microwave-amplifiers",
    "mixers",
    "microwave-oscillators",
  ],
  "microprocessors-microcontrollers": [
    "8085-pin-diagram",
    "register-organization",
    "alu-and-flags",
    "bus-structure",
    "memory-and-io-map",
    "machine-cycles",
    "8086-pin-diagram",
    "segmented-memory",
    "register-set",
    "minimum-maximum-mode",
    "bus-interface-execution-unit",
    "8085-instruction-set",
    "8086-instruction-set",
    "data-transfer-instructions",
    "arithmetic-instructions",
    "logical-instructions",
    "branch-instructions",
    "stack-instructions",
    "immediate-addressing",
    "register-addressing",
    "direct-addressing",
    "indirect-addressing",
    "indexed-addressing",
    "relative-addressing",
    "memory-interfacing",
    "io-interfacing",
    "8255-pio",
    "8254-pit",
    "8251-usart",
    "8259-pic",
    "dac-adc-interfacing",
    "8085-interrupts",
    "8086-interrupts",
    "hardware-software-interrupts",
    "interrupt-priority",
    "interrupt-service-routine",
    "timer-modes",
    "counter-operation",
    "watchdog-timer",
    "embedded-system-design",
    "real-time-systems",
    "rtos-concepts",
    "task-scheduling",
    "inter-task-communication",
    "uart-spi-i2c",
    "can-bus",
    "low-power-embedded-design",
    "arm-architecture",
    "arm-register-set",
    "arm-instruction-set",
    "thumb-instruction-set",
    "arm-pipeline",
    "cortex-m-series-overview",
  ],
  "digital-signal-processing": [
    "signal-classification",
    "basic-discrete-sequences",
    "signal-operations",
    "energy-and-power",
    "definition-roc",
    "z-transform-properties",
    "inverse-z-transform",
    "system-function-poles-zeros",
    "dft-definition",
    "idft",
    "dft-properties",
    "circular-convolution",
    "linear-vs-circular-convolution",
    "overlap-add-overlap-save",
    "dit-fft",
    "dif-fft",
    "butterfly-diagram",
    "computational-complexity",
    "inverse-fft",
    "fir-filter-structure",
    "linear-phase-fir",
    "window-method-design",
    "frequency-sampling-method",
    "park-mcclellan-method",
    "iir-filter-structure",
    "direct-form-i-ii",
    "butterworth-filter-design",
    "chebyshev-filter-design",
    "elliptic-filter-design",
    "analog-to-digital-filter-conversion",
    "bilinear-transformation",
    "impulse-invariance-method",
    "frequency-transformation",
    "fir-vs-iir-comparison",
    "dtft",
    "power-spectral-density",
    "windowing-effects",
    "short-time-fourier-transform",
    "dsp-architecture",
    "harvard-architecture",
    "mac-unit",
    "dsp-programming-basics",
  ],
  "vlsi-design": [
    "mos-transistor-review",
    "spice-models",
    "transistor-sizing",
    "fabrication-process-steps",
    "photolithography",
    "doping-techniques",
    "oxidation-and-diffusion",
    "design-rules",
    "cmos-logic-design",
    "stick-diagrams",
    "layout-design",
    "pass-transistor-logic",
    "transmission-gate-logic",
    "cmos-flip-flops",
    "dynamic-logic",
    "domino-logic",
    "sense-amplifiers",
    "static-timing-analysis",
    "setup-hold-time-vlsi",
    "clock-skew-and-jitter",
    "timing-constraints",
    "sources-of-power-dissipation",
    "dynamic-power-reduction",
    "static-power-reduction",
    "clock-gating",
    "multi-vdd-design",
    "fpga-architecture",
    "lut-based-design",
    "clb-iob-routing",
    "fpga-vs-asic",
    "fpga-design-flow",
    "verilog-basics",
    "verilog-data-types",
    "verilog-modules-and-ports",
    "behavioral-modeling",
    "dataflow-modeling",
    "structural-modeling",
    "testbench-writing",
    "vhdl-basics",
    "verilog-vs-vhdl",
    "floorplanning",
    "placement",
    "routing",
    "drc-and-lvs",
    "parasitic-extraction",
  ],
  "computer-organization": [
    "binary-octal-hexadecimal",
    "number-conversions",
    "signed-representation",
    "twos-complement",
    "floating-point-representation-ieee-754",
    "binary-addition-subtraction",
    "binary-multiplication",
    "booth-algorithm",
    "binary-division",
    "floating-point-arithmetic",
    "overflow-and-underflow",
    "memory-hierarchy",
    "sram-vs-dram",
    "cache-memory",
    "cache-mapping-techniques",
    "cache-replacement-policies",
    "virtual-memory",
    "paging-and-segmentation",
    "io-techniques-polling",
    "interrupt-driven-io",
    "dma",
    "io-interfaces",
    "buses-types-and-protocols",
    "pipeline-stages",
    "pipeline-hazards",
    "data-hazards",
    "control-hazards",
    "structural-hazards",
    "forwarding-and-stalling",
    "pipeline-performance-metrics",
    "direct-mapped-cache",
    "fully-associative-cache",
    "set-associative-cache",
    "cache-write-policies",
    "cache-coherence",
    "cache-performance",
    "risc-characteristics",
    "cisc-characteristics",
    "comparison-table",
    "modern-processor-trends",
  ],
  "tools-software": [
    "matlab-basics",
    "matrix-operations",
    "signal-processing-toolbox",
    "control-system-toolbox",
    "communications-toolbox",
    "plotting-and-visualization",
    "simulink-introduction",
    "block-library",
    "modeling-control-systems",
    "modeling-communication-systems",
    "hardware-in-loop",
    "ltspice-basics",
    "dc-operating-point",
    "transient-analysis",
    "ac-frequency-analysis",
    "component-libraries",
    "cadence-virtuoso-basics",
    "schematic-entry",
    "simulation-spectre",
    "layout-editor",
    "drc-lvs-cadence",
    "vivado-introduction",
    "rtl-design-flow",
    "synthesis-and-implementation",
    "constraints-xdc",
    "fpga-programming",
    "multisim-basics",
    "analog-circuit-simulation",
    "digital-circuit-simulation",
    "mixed-signal-simulation",
    "proteus-introduction",
    "circuit-schematic",
    "microcontroller-simulation",
    "pcb-design-basics",
    "component-library",
  ],
  "ece-projects-labs": [
    "diode-characteristics",
    "bjt-characteristics",
    "common-emitter-amplifier-lab",
    "op-amp-applications-lab",
    "filter-design-lab",
    "oscillator-design-lab",
    "logic-gate-verification",
    "adder-subtractor-lab",
    "mux-demux-lab",
    "flip-flop-lab",
    "counter-design-lab",
    "fsm-design-lab",
    "sampling-and-reconstruction",
    "dft-and-fft-lab",
    "fir-filter-design-lab",
    "iir-filter-design-lab",
    "speech-processing-lab",
    "8085-programs",
    "8086-programs",
    "assembly-language-programs",
    "interfacing-experiments",
    "interrupt-programs",
    "am-modulation-lab",
    "fm-modulation-lab",
    "pcm-lab",
    "digital-modulation-lab",
    "optical-fiber-lab",
    "led-blinking-gpio",
    "uart-serial-communication",
    "temperature-sensor-interfacing",
    "lcd-display-project",
    "pwm-motor-control",
    "adc-data-acquisition",
    "i2c-spi-projects",
    "rtos-based-project",
    "iot-embedded-project",
  ],
};

// Lesson display name formatter
function formatLessonName(filename: string): string {
  return filename
    .replace(/\.(jsx|tsx|js|ts)$/, "")
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

// ─── SERVER-SIDE: reads real filesystem ───────────────────────────────────────
export async function getSubjectsFromFS(): Promise<Subject[]> {
  const fs = await import("fs");
  const path = await import("path");

  const contentRoot = path.join(process.cwd(), "content");
  if (!fs.existsSync(contentRoot)) return [];

  // Use defined metadata IDs to ensure consistency across environments
  const subjectIds = Object.keys(SUBJECT_META);

  const subjects: Subject[] = subjectIds
    .filter((id) => fs.existsSync(path.join(contentRoot, id)))
    .map((subjectId) => {
      const subjectPath = path.join(contentRoot, subjectId);
      const meta = SUBJECT_META[subjectId];

      const topicDirs = fs
        .readdirSync(subjectPath, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name);

      if (TOPIC_ORDER[subjectId]) {
        const order = TOPIC_ORDER[subjectId];
        topicDirs.sort((a, b) => {
          const idxA = order.indexOf(a);
          const idxB = order.indexOf(b);
          if (idxA === -1 && idxB === -1) return 0;
          if (idxA === -1) return 1;
          if (idxB === -1) return -1;
          return idxA - idxB;
        });
      }

      const topics: Topic[] = topicDirs.map((topicId) => {
      const topicPath = path.join(subjectPath, topicId);
      const lessonFiles = fs
        .readdirSync(topicPath)
        .filter((f) => /\.(jsx|tsx|js|ts)$/.test(f));

      const lessons: Lesson[] = lessonFiles.map((file) => ({
        id: file.replace(/\.(jsx|tsx|js|ts)$/, ""),
        name: formatLessonName(file),
        topicId,
        subjectId,
        path: `../content/${subjectId}/${topicId}/${file}`,
      }));

      if (LESSON_ORDER[topicId]) {
        const order = LESSON_ORDER[topicId];
        lessons.sort((a, b) => order.indexOf(a.id) - order.indexOf(b.id));
      }

      return {
        id: topicId,
        name: TOPIC_LABELS[topicId] ?? formatLessonName(topicId),
        subjectId,
        lessons,
      };
    });

    return {
      id: subjectId,
      name: meta.label,
      description: meta.description,
      icon: meta.icon,
      color: meta.color,
      topics,
    };
    });

  return subjects;
}

export async function getSubjectFromFS(subjectId: string): Promise<Subject | null> {
  const fs = await import("fs");
  const path = await import("path");
  const contentRoot = path.join(process.cwd(), "content");
  const subjectPath = path.join(contentRoot, subjectId);

  if (!fs.existsSync(subjectPath) || !SUBJECT_META[subjectId]) return null;

  const meta = SUBJECT_META[subjectId];

  const topicDirs = fs
    .readdirSync(subjectPath, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  if (TOPIC_ORDER[subjectId]) {
    const order = TOPIC_ORDER[subjectId];
    topicDirs.sort((a, b) => order.indexOf(a) - order.indexOf(b));
  }

  const topics: Topic[] = topicDirs.map((topicId) => {
    const topicPath = path.join(subjectPath, topicId);
    const lessonFiles = fs
      .readdirSync(topicPath)
      .filter((f) => /\.(jsx|tsx|js|ts)$/.test(f));

    const lessons: Lesson[] = lessonFiles.map((file) => ({
      id: file.replace(/\.(jsx|tsx|js|ts)$/, ""),
      name: formatLessonName(file),
      topicId,
      subjectId,
      path: `../content/${subjectId}/${topicId}/${file}`,
    }));

    if (LESSON_ORDER[topicId]) {
      const order = LESSON_ORDER[topicId];
      lessons.sort((a, b) => order.indexOf(a.id) - order.indexOf(b.id));
    }

    return {
      id: topicId,
      name: TOPIC_LABELS[topicId] ?? formatLessonName(topicId),
      subjectId,
      lessons,
    };
  });

  return {
    id: subjectId,
    name: meta.label,
    description: meta.description,
    icon: meta.icon,
    color: meta.color,
    topics,
  };
}

export async function getTopicFromFS(subjectId: string, topicId: string): Promise<Topic | null> {
  const subject = await getSubjectFromFS(subjectId);
  return subject?.topics.find((t) => t.id === topicId) ?? null;
}

